### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by xiCrystalx** [The-Nexus-Project/Limitless-6#40]
### What happened?

Game crashing at start

### Pack Version

Version: 1.12.0

### To Reproduce

1.
[latest.log](https://github.com/The-Nexus-Project/Limitless-6/files/10462803/latest.log)

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
[03:33:53] [main/INFO]: ModLauncher running: args [--username, xiCrystalx, --version, forge-43.2.3, --gameDir, C:\Users\kryst\curseforge\minecraft\Instances\TNP Limitless 6 - LL6 (1), --assetsDir, C:\Users\kryst\curseforge\minecraft\Install\assets, --assetIndex, 1.19, --uuid, bbf1f5c892a54d40b77a190e133dfb08, --accessToken, ????????, --clientId, MjJlN2YxZTQtZjYwMy00MjJlLWJkZjMtM2FlMGM0MTViODE1, --xuid, 2535463000400455, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.3, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[03:33:53] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[03:33:53] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/kryst/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT
[03:33:53] [main/WARN]: Mod file C:\Users\kryst\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.3\fmlcore-1.19.2-43.2.3.jar is missing mods.toml file
[03:33:53] [main/WARN]: Mod file C:\Users\kryst\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.3\javafmllanguage-1.19.2-43.2.3.jar is missing mods.toml file
[03:33:53] [main/WARN]: Mod file C:\Users\kryst\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.3\lowcodelanguage-1.19.2-43.2.3.jar is missing mods.toml file
[03:33:53] [main/WARN]: Mod file C:\Users\kryst\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.3\mclanguage-1.19.2-43.2.3.jar is missing mods.toml file
[03:33:53] [main/INFO]: Found mod file fmlcore-1.19.2-43.2.3.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3249a1ce
[03:33:53] [main/INFO]: Found mod file javafmllanguage-1.19.2-43.2.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3249a1ce
[03:33:53] [main/INFO]: Found mod file lowcodelanguage-1.19.2-43.2.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3249a1ce
[03:33:53] [main/INFO]: Found mod file mclanguage-1.19.2-43.2.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3249a1ce
[03:33:53] [main/INFO]: Found mod file client-1.19.2-20220805.130853-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3249a1ce
[03:33:53] [main/INFO]: Found mod file forge-1.19.2-43.2.3-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3249a1ce
[03:33:53] [main/INFO]: No dependencies to load found. Skipping!
[03:33:54] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-43.2.3, --gameDir, C:\Users\kryst\curseforge\minecraft\Instances\TNP Limitless 6 - LL6 (1), --assetsDir, C:\Users\kryst\curseforge\minecraft\Install\assets, --uuid, bbf1f5c892a54d40b77a190e133dfb08, --username, xiCrystalx, --assetIndex, 1.19, --accessToken, ????????, --clientId, MjJlN2YxZTQtZjYwMy00MjJlLWJkZjMtM2FlMGM0MTViODE1, --xuid, 2535463000400455, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[03:33:59] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[03:34:00] [Render thread/WARN]: Assets URL 'union:/C:/Users/kryst/curseforge/minecraft/Install/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23145!/assets/.mcassetsroot' uses unexpected schema
[03:34:00] [Render thread/WARN]: Assets URL 'union:/C:/Users/kryst/curseforge/minecraft/Install/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23145!/data/.mcassetsroot' uses unexpected schema
[03:34:00] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[03:34:01] [Render thread/INFO]: Setting user: xiCrystalx
[03:34:01] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[03:34:06] [Render thread/WARN]: Failed to create window: 
com.mojang.blaze3d.platform.Window$WindowInitFailed: GLFW error 65542: WGL: The driver does not appear to support OpenGL
	at com.mojang.blaze3d.platform.Window.m_85412_(Window.java:246) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7]
	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7]
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2024) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2197) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7]
	at net.minecraftforge.client.loading.NoVizFallback.lambda$fallback$0(NoVizFallback.java:14) ~[forge-1.19.2-43.2.3-universal.jar%23150!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.fml.loading.progress.EarlyProgressVisualization$Visualization.handOffWindow(EarlyProgressVisualization.java:50) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?]
	at net.minecraftforge.fml.loading.progress.EarlyProgressVisualization.handOffWindow(EarlyProgressVisualization.java:35) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?]
	at com.mojang.blaze3d.platform.Window.<init>(Window.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?]
	at net.minecraft.client.renderer.VirtualScreen.m_110872_(VirtualScreen.java:21) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:442) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
```

### Anything else to add?

Any idea what happened? I have latest NVidia drivers and latest Java update :/ It's just crashing after clicking "play" in MC launcher.

**Comment by xiCrystalx** [comment]
Problem solved. My GPU just uninstaled itself :D
