### ISSUE TITLE
[Issue]: Server crash - java.lang.NullPointerException: minecraft:the_nether is not a valid level stem key. 

### ISSUE THREAD

**Issue by osirus31** [The-Nexus-Project/Limitless-6#55]
### What happened?

the Minecraft server will no longer start.

I have tried deleting the DIM-1 folder and tried just deleting the contents of DIM-1/region

java.lang.NullPointerException: minecraft:the_nether is not a valid level stem key. This is likely the result of a broken level.dat, likely caused by moving this world between MC versions.
	at net.minecraft.server.MinecraftServer.handler$zbh000$IE_appendSurfaceRules(MinecraftServer.java:2928) ~[server-1.19.2-20220805.130853-srg.jar%231133!/:?]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:375) ~[server-1.19.2-20220805.130853-srg.jar%231133!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:300) ~[server-1.19.2-20220805.130853-srg.jar%231133!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:165) ~[server-1.19.2-20220805.130853-srg.jar%231133!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[server-1.19.2-20220805.130853-srg.jar%231133!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%231133!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

### Pack Version

Version: LL6 v1.16

### To Reproduce

1. just updating and starting server.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
Error:
[26Feb2023 22:55:05.161] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NullPointerException: minecraft:the_nether is not a valid level stem key. This is likely the result of a broken level.dat, likely caused by moving this world between MC versions.
	at net.minecraft.server.MinecraftServer.handler$zbh000$IE_appendSurfaceRules(MinecraftServer.java:2928) ~[server-1.19.2-20220805.130853-srg.jar%231133!/:?]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:375) ~[server-1.19.2-20220805.130853-srg.jar%231133!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:300) ~[server-1.19.2-20220805.130853-srg.jar%231133!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:165) ~[server-1.19.2-20220805.130853-srg.jar%231133!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[server-1.19.2-20220805.130853-srg.jar%231133!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%231133!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by osirus31** [comment]
Full log file
[latest.log](https://github.com/The-Nexus-Project/Limitless-6/files/10834996/latest.log)

**Comment by Gbergz** [comment]
Send the level.dat file and ill fix it for you, once I send it back just replace the one you have

**Comment by osirus31** [comment]
Is it possible to explain the fix or provide a link to an explanation?  I am able to edit NBT without issue, just need to know what I need to delete/update.  My server runs 24/7 so I would rather be able to plan the stop/start.

**Comment by Gbergz** [comment]
I would explain, but I don't have the time to explain the fix right now. Send it and I'll fix it

**Comment by joeblob8354** [comment]
Also having this same issue, is there a fix for this yet?

**Comment by Gbergz** [comment]
@joeblob8354 Join the TNP discord and send your level.dat file of your world and I'll send it back fixed.
