### ISSUE TITLE
[Issue]: In some cases "Drippy Loading Screen" will tank performance

### ISSUE THREAD

**Issue by SystemlessDev** [The-Nexus-Project/Limitless-6#64]
### What happened?

The version of drippy loading screen that this mod uses, 1.6.6, has a bug in it where it will spam reload the sound engine in some situations. This will obviously kill performance in every way.

[Here's the Mixin at fault](https://github.com/Keksuccino/Drippy-Loading-Screen/blob/de57e1fe379a3a34f12357eb4d9976ffec5bdef4/src/main/java/de/keksuccino/drippyloadingscreen/mixin/client/MixinSoundEngine.java). The sound engine is reloaded every tick if it fails to load properly. Which obviously leads to the sound engine being reloaded all the time, and the log being spammed with the stacktrace below once every tick. 

You got two options to fix this issue. You can either set the config option `custom_sound_engine_reloading` to false, or update the mod to a more recent version. 

### Pack Version

Version: v1.19.0

### To Reproduce

N/A

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
[14:24:25] [Render thread/INFO]: Audio device was lost!
[14:24:25] [Render thread/INFO]: [DRIPPY LOADING SCREEN] Reloading sound engine..
[14:24:25] [Render thread/WARN]: Failed to reset device: Invalid Device
[14:24:25] [Render thread/ERROR]: Get attributes size2218739250048: Invalid device.
[14:24:25] [Render thread/ERROR]: Error starting SoundSystem. Turning off sounds & music
java.lang.IllegalStateException: Failed to get OpenAL attributes
	at com.mojang.blaze3d.audio.Library.m_83703_(Library.java:212) ~[client-1.19.2-20220805.130853-srg.jar%231243!/:?]
	at com.mojang.blaze3d.audio.Library.m_231084_(Library.java:168) ~[client-1.19.2-20220805.130853-srg.jar%231243!/:?]
	at net.minecraft.client.sounds.SoundEngine.m_120323_(SoundEngine.java:101) ~[client-1.19.2-20220805.130853-srg.jar%231243!/:?]
	at net.minecraft.client.sounds.SoundEngine.m_120239_(SoundEngine.java:93) ~[client-1.19.2-20220805.130853-srg.jar%231243!/:?]
	at net.minecraft.client.sounds.SoundEngine.m_120302_(SoundEngine.java:216) ~[client-1.19.2-20220805.130853-srg.jar%231243!/:?]
	at net.minecraft.client.sounds.SoundManager.m_120389_(SoundManager.java:249) ~[client-1.19.2-20220805.130853-srg.jar%231243!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1801) ~[client-1.19.2-20220805.130853-srg.jar%231243!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078) ~[client-1.19.2-20220805.130853-srg.jar%231243!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%231243!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%231243!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%231243!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
```

### Anything else to add?

Thanks! :)

**Comment by Gbergz** [comment]
Thanks for report, can't update the mod right now due to some issues.
Will save this in my todo list for the future!

**Comment by SystemlessDev** [comment]
You can disable the sound reloading feature however. You don't seem to make use of that feature regardless.

**Comment by Gbergz** [comment]
Yes, that I will do.
