### ISSUE TITLE
[Issue]: Game crashed

### ISSUE THREAD

**Issue by Repa1253** [The-Nexus-Project/Limitless-6#9]
### What happened?

A bug happened!

### Pack Version

Version: 1.19.2

### To Reproduce

Haven't figured that out

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2022-10-20 22:35:29
Description: Exception generating new chunk

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.phys.shapes.VoxelShape.m_83216_(double, double, double)" because "shape" is null
	at com.abdelaziz.canary.common.entity.movement.ChunkAwareBlockCollisionSweeper.getCollidedShape(ChunkAwareBlockCollisionSweeper.java:114) ~[canary-mc1.19.2-0.0.4.jar%23206!/:0.0.4] {re:classloading}
	at com.abdelaziz.canary.common.entity.movement.ChunkAwareBlockCollisionSweeper.computeNext(ChunkAwareBlockCollisionSweeper.java:268) ~[canary-mc1.19.2-0.0.4.jar%23206!/:0.0.4] {re:classloading}
	at com.abdelaziz.canary.common.entity.CanaryEntityCollisions.doesBoxCollideWithBlocks(CanaryEntityCollisions.java:46) ~[canary-mc1.19.2-0.0.4.jar%23206!/:0.0.4] {re:mixin,re:classloading}
	at net.minecraft.world.level.CollisionGetter.m_45756_(CollisionGetter.java:526) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:computing_frames,re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.CollisionViewMixin,pl:mixin:A}
	at net.minecraft.world.level.CollisionGetter.m_45772_(CollisionGetter.java:40) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:computing_frames,re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.CollisionViewMixin,pl:mixin:A}
	at net.minecraft.world.level.NaturalSpawner.m_220450_(NaturalSpawner.java:367) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,re:classloading,pl:mixin:APP:the_bumblezone.mixins.json:entities.MobSpawnLocationMixin,pl:mixin:APP:itshallnottick.mixins.json:WorldEntitySpawnerOptimizationMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.m_6929_(NoiseBasedChunkGenerator.java:460) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.NoiseBasedChunkGeneratorAccessor,pl:mixin:APP:canary.mixins.json:gen.cached_generator_settings.NoiseChunkGeneratorMixin,pl:mixin:APP:byg.mixins.json:access.NoiseBasedChunkGeneratorAccess,pl:mixin:APP:blueprint.mixins.json:NoiseBasedChunkGeneratorMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_196757_(ChunkStatus.java:174) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:341) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:phosphophyllite.mixins.json:ChunkMapMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23120!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:phosphophyllite.mixins.json:ChunkMapMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.abdelaziz.canary.common.entity.movement.ChunkAwareBlockCollisionSweeper.getCollidedShape(ChunkAwareBlockCollisionSweeper.java:114) ~[canary-mc1.19.2-0.0.4.jar%23206!/:0.0.4] {re:classloading}
	at com.abdelaziz.canary.common.entity.movement.ChunkAwareBlockCollisionSweeper.computeNext(ChunkAwareBlockCollisionSweeper.java:268) ~[canary-mc1.19.2-0.0.4.jar%23206!/:0.0.4] {re:classloading}
	at com.abdelaziz.canary.common.entity.CanaryEntityCollisions.doesBoxCollideWithBlocks(CanaryEntityCollisions.java:46) ~[canary-mc1.19.2-0.0.4.jar%23206!/:0.0.4] {re:mixin,re:classloading}
	at net.minecraft.world.level.CollisionGetter.m_45756_(CollisionGetter.java:526) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:computing_frames,re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.CollisionViewMixin,pl:mixin:A}
	at net.minecraft.world.level.CollisionGetter.m_45772_(CollisionGetter.java:40) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:computing_frames,re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.CollisionViewMixin,pl:mixin:A}
	at net.minecraft.world.level.NaturalSpawner.m_220450_(NaturalSpawner.java:367) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,re:classloading,pl:mixin:APP:the_bumblezone.mixins.json:entities.MobSpawnLocationMixin,pl:mixin:APP:itshallnottick.mixins.json:WorldEntitySpawnerOptimizationMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.m_6929_(NoiseBasedChunkGenerator.java:460) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.NoiseBasedChunkGeneratorAccessor,pl:mixin:APP:canary.mixins.json:gen.cached_generator_settings.NoiseChunkGeneratorMixin,pl:mixin:APP:byg.mixins.json:access.NoiseBasedChunkGeneratorAccess,pl:mixin:APP:blueprint.mixins.json:NoiseBasedChunkGeneratorMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_196757_(ChunkStatus.java:174) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:341) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:phosphophyllite.mixins.json:ChunkMapMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23120!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:phosphophyllite.mixins.json:ChunkMapMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
-- Chunk to be generated --
Details:
	Location: -28,18
	Position hash: 81604378596
	Generator: net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator@266ad643
Stacktrace:
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:phosphophyllite.mixins.json:ChunkMapMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23120!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:phosphophyllite.mixins.json:ChunkMapMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Repa0206'/1279, l='ServerLevel[New World]', x=-280.59, y=73.00, z=215.12]]
	Chunk stats: 3177
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,72,-16), Section: (at 0,8,0 in -5,4,-1; chunk contains blocks -80,-64,-16 to -65,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 25216 game time, 25216 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 124142 (now: false), thunder time: 19300 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:869) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
```

**Comment by Repa1253** [comment]
I have started a new save since then and it hasn't happend again. I could make a new crash report if it ever happens again.
